#!/bin/sh
PIDFILE="/var/run/ntpd.pid"
NTPD_OPTS="-p time.google.com"

has_ip()
{
  ifconfig wlan0 | grep -c inet
}

status()
{
  pid="$(cat "$PIDFILE" 2>/dev/null)"
  if [ "$pid" ]; then
    kill -0 "$pid" 2>/dev/null && echo "PID: $pid" || return 1
  fi
}

start()
{
  echo "Setting kernel timezone via hwclock..."
  modprobe snx_rtc && hwclock -s && modprobe -r snx_rtc

  echo "Starting ntpd..."
  while [ $(has_ip) -eq 0 ]; do
    echo "No IP yet, waiting..."
    sleep 3
  done
  ntpd -q -n $NTPD_OPTS
  sleep 2
  hwclock -t
  sleep 2
  ntpd $NTPD_OPTS
}

stop()
{
  pid="$(cat "$PIDFILE" 2>/dev/null)"
  if [ "$pid" ]; then
     kill $pid || rm "$PIDFILE"
  fi
}

if [ $# -eq 0 ]; then
  start
else
  case $1 in start|stop|status)
    $1
    ;;
  esac
fi
