#!/bin/sh

OSD_LINE1=`hostname`
#OSD_LINE1="mycam"

start()
{
  echo "Setting OSD details"

  snx_isp_ctl -c 0 \
      --osdset-en 1 \
      --osdset-ts 1 \
      --osdset-gain 2 \
      --osdset-datastr "$OSD_LINE1" \
      --osdset-template "0123456789./-:$OSD_LINE1" \
      --osdset-txtcolor 0xFFFFFF \
      --osdset-bgcolor 0x000000 \
      --osdset-bgtransp 0x1 \
     --osdset-position 0,1020

# osd position for big txt (gain 2)
#   original top: 40,20
#   1080p bottom: 0,1020
#   720p  bottom: 0,660
}

stop()
{
  echo "Restoring default OSD settings"

  snx_isp_ctl -c 0 \
      --osdset-en 0 \
      --osdset-ts 0 \
      --osdset-gain 1 \
      --osdset-datastr "" \
      --osdset-template "" \
      --osdset-position 0,0

  #rm -f "$STATUSFILE"
}

if [ $# -eq 0 ]; then
  start
else
  case $1 in start|stop)
    $1
    ;;
  esac
fi
