#!/bin/sh

start()
{
  echo "Configuring camera image settings"
  snx_isp_ctl \
      --sensorset-mir 0 \
      --sensorset-flip 0
  echo 0x40 > /proc/isp/filter/brightness
  echo 0x20 > /proc/isp/filter/contrast
  echo 0x75 > /proc/isp/filter/gamma
  echo 0x0 > /proc/isp/filter/hue
  echo 0x40 > /proc/isp/filter/saturation
  echo 0x3 > /proc/isp/filter/sharpness
}

stop()
{
  echo "Restoring default image settings"

  snx_isp_ctl \
      --sensorset-mir 0 \
      --sensorset-flip 0
  echo 0x40 > /proc/isp/filter/brightness
  echo 0x20 > /proc/isp/filter/contrast
  echo 0x64 > /proc/isp/filter/gamma
  echo 0x0 > /proc/isp/filter/hue
  echo 0x40 > /proc/isp/filter/saturation
  echo 0x3 > /proc/isp/filter/sharpness
}

if [ $# -eq 0 ]; then
  start
else
  case $1 in start|stop)
    $1
    ;;
  esac
fi
